Repository ZB-Online/uratcha-pedia, pull requests merged in 2021-12, with the labels that each got.

#3 #2 test
  test.js
Labels: bug

#5 #4 test
  test.js
Labels: bug

#16 Feat: #12 Carousel Function added
  dist/bundle.js
  dist/bundle.js.map
  package-lock.json
  public/css/common.css
  public/css/main.css
  public/index.html
  public/js/app.js
  public/js/modules/carousel.js
  public/js/modules/movies.js
  webpack.config.js
Labels: Feature, ReviewMe

#23 Refactor : movie api
  server/controllers/movies.js
  server/controllers/reviews.js
  server/controllers/stars.js
  server/controllers/users.js
  server/routes/movies.js
  server/utils/resData.js
  server/utils/resMessage.js
  server/utils/themovie.js
Labels: Refactor, ReviewMe

#33 #30 Refactor: getMoviesDetailsById(), getMoviesWithCountry() 성능 최적화
  package-lock.json
  server/utils/themovie.js
Labels: Refactor, ReviewMe

#35 #34 Feat: 평균 별점 순위 배열에 포함되는 영화 정보를 the-movie-api를 사용해 구성하는 로직 추가
  .DS_Store
  package-lock.json
  public/js/modules/api.js
  public/js/modules/movies.js
  server/controllers/movies.js
  server/controllers/users.js
  server/dao/movies.js
  server/routes/movies.js
  server/utils/themovie.js
Labels: Feature, Fix

#49 Merge: temp
  package-lock.json
  public/css/common.css
  public/css/main.css
  public/css/movie-detail.css
  public/css/popup.css
  public/css/search-result.css
  public/img/no_image.png
  public/img/uratcha_logo.PNG
  public/index.html
  public/js/Components/MovieDetails.js
  public/js/Components/MovieRanking.js
  public/js/Components/MyScoredMovies.js
  public/js/Components/SearchResult.js
  public/js/Components/SimilarWorks.js
  public/js/Components/StarsGraph.js
  public/js/Components/Wrapper.js
  public/js/Components/global/BoxOfficeRankingCarousel.js
  public/js/Components/global/HighestRankingCarousel.js
  public/js/Components/global/MovieCommentCarousel.js
  public/js/Components/global/MyScoredMoviesCarousel.js
  public/js/Components/global/SearchedMovieCarousel.js
  public/js/app.js
  public/js/eventListeners.js
  public/js/modules/api.js
  public/js/modules/movies.js
  public/js/pages/HomePage.js
  public/js/pages/MovieDetailsPage.js
  public/js/pages/MyPage.js
  public/js/pages/SearchResultPage.js
  public/js/utils/carousel.js
  public/js/utils/useFetch.js
  server/controllers/movies.js
  server/controllers/reviews.js
  server/controllers/stars.js
  server/controllers/users.js
  server/dao/reviews.js
  server/dao/stars.js
  server/middleware/auth.js
  server/models/movies.js
  server/models/reviews.js
  server/models/stars.js
  server/models/users.js
  server/routes/movies.js
  server/routes/stars.js
  server/utils/themovie.js
  webpack.config.js
Labels: MergeConflict

#56 Feat51/carousel star rate
  front/src/css/main.css
  front/src/css/popup.css
  front/src/img/uratcha_logo_small.png
  front/src/js/components/MovieDetails.js
  front/src/js/components/MovieRanking.js
  front/src/js/components/MyScoredMovies.js
  front/src/js/components/SearchResult.js
  front/src/js/components/SimilarWorks.js
  front/src/js/components/Wrapper.js
  front/src/js/components/global/BoxOfficeRankingCarousel.js
  front/src/js/components/global/HighestRankingCarousel.js
  front/src/js/components/global/MyScoredMoviesCarousel.js
  front/src/js/components/global/SearchedMovieCarousel.js
  front/src/js/pages/HomePage.js
  front/src/js/pages/MovieDetailsPage.js
Labels: Feature, Refactor

#54 auth 기능 구현
  back/server/controllers/reviews.js
  back/server/controllers/stars.js
  back/server/controllers/users.js
  back/server/dao/reviews.js
  back/server/middleware/auth.js
  front/src/css/movie-detail.css
  front/src/js/App.js
  front/src/js/components/MovieDetails.js
  front/src/js/components/Wrapper.js
  front/src/js/eventListeners.js
  front/src/js/pages/HomePage.js
  front/src/js/pages/MovieDetailsPage.js
  front/src/js/pages/MyPage.js
  front/src/js/pages/SearchResultPage.js
  front/src/js/store/reviews.js
  front/src/js/utils/cookie.js
  front/src/js/utils/debounce.js
  front/src/js/utils/fetch.js
Labels: Feature, Fix, ReviewMe

#71 #68 Refactor: movie details fetch 모듈화 및 fetch 함수 이름 수정
  front/src/js/pages/MovieDetailsPage.js
  front/src/js/services/movies/movie.js
  front/src/js/services/reviews/reviews.js
  front/src/js/services/scores/scores.js
Labels: Refactor, ReviewMe

#76 #74 Fix: 장르가 비어 있는 영화의 경우 비슷한 작품은 no similar works 렌더
  front/src/js/components/SimilarWorks.js
Labels: Fix

#77 Fix:75 모듈화 및 리팩토링 작업
  back/server/dao/reviews.js
  back/server/dao/stars.js
  front/src/css/movie-detail.css
  front/src/js/pages/HomePage.js
  front/src/js/pages/MovieDetailsPage.js
  front/src/js/pages/MyPage.js
  front/src/js/pages/SearchResultPage.js
  front/src/js/services/index.js
  front/src/js/services/movies.js
  front/src/js/services/reviews.js
  front/src/js/services/scores.js
  front/src/js/temp/index.js
  front/src/js/temp/movies.js
  front/src/js/temp/reviews.js
  front/src/js/temp/scores.js
  front/src/js/temp/users.js
Labels: Refactor
